# Generated by Django 5.2.4 on 2025-08-09 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_application_options_and_more"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[("PEN", "Pending"), ("APP", "Approved"), ("REJ", "Rejected")],
                default="PEN",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("user", "event")},
        ),
    ]
