# Generated by Django 5.2.4 on 2025-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Име")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Съобщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата/Час"),
                ),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="Отговорено"),
                ),
                (
                    "reply",
                    models.TextField(
                        blank=True, null=True, verbose_name="Отговор от админ"
                    ),
                ),
            ],
        ),
    ]
