# Generated by Django 5.2.4 on 2025-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.png",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
