# Generated by Django 5.2.4 on 2025-07-28 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={},
        ),
        migrations.RemoveField(
            model_name="location",
            name="gps_lat",
        ),
        migrations.RemoveField(
            model_name="location",
            name="gps_lon",
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 7, 28, 8, 12, 7, 231093, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 7, 28, 8, 12, 24, 180937, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(max_length=100),
        ),
    ]
